# -*- coding: utf-8 -*-
"""assignment13.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODUGcfuKo-358HW62Be58SfaNkeAmyrF

**1.to check whether a string starts with specified character**
"""

string = "sharanya,devi"
print(string.startswith("sha"))

"""**2.to print the index of a character in a string**"""

str1 = "devi sharanya"
for index, char in enumerate(str1):
  print("current character",char,"position at",index)

"""**3.to iterate over dictionaries using for loops**"""

d = {'x': 1, 'y': 2, 'z':3}
for dict_key,dict_value in d.items():
  print(dict_key,'->',dict_value)

"""**4.to remove the givenkey from the dictionary**"""

myDict = {'a':1,'b':2,'c':3,'d':4}
print(myDict)
if 'a' in myDict:
  del myDict['a']
print(myDict)